# Common sections
defaults: &defaults
  docker:
    - image: dmp1ce/archlinux-yay
  steps:
    - run:
        name: Update packages
        command: sudo pacman -Syu --noconfirm
    - run:
        name: Build package
        command: yay --useask -S --noconfirm ${CIRCLE_JOB}

    - store_artifacts:
        path: ../.cache/yay/${CIRCLE_JOB}/*.tar.zst
        destination: artifact-file2
    - store_artifacts:
        path: ../.cache/yay/
        destination: artifact-file3
    - store_artifacts:
        path: ../.cache/yay/${CIRCLE_JOB}
        destination: artifact-file5


# Main
version: 2
jobs:
  whirlpool-gui-appimage:
    <<: *defaults
  bisq-bin:
    <<: *defaults

workflows:
  version: 2
  build:
    jobs:
      - whirlpool-gui-appimage
      - bisq-bin
