# Common sections
defaults: &defaults
  docker:
    - image: dmp1ce/archlinux-yay
  steps:
    - run:
        name: Update packages
        command: sudo pacman -Syu --noconfirm
    - run:
        name: Build package
        command: yay --useask -S --noconfirm ${CIRCLE_JOB}

# Main
version: 2
jobs:
  whirlpool-gui-appimage:
    <<: *defaults
  bisq-bin:
    <<: *defaults

workflows:
  version: 2
  build:
    jobs:
      - whirlpool-gui-appimage
      - bisq-bin
