# Common sections
defaults: &defaults
  docker:
    - image: archlinux:base-devel
  steps:
    - run:
        name: install yay deps
        command: pacman -Sy --noconfirm git go
    - run:
        name: install yay
        command: git clone https://aur.archlinux.org/yay.git  && cd yay && makepkg -si --noconfirm && cd .. 
    - run:
        name: Build package
        command: yay --useask -S --noconfirm ${CIRCLE_JOB}

    - store_artifacts:
        path: ../.cache/yay/${CIRCLE_JOB}/*.tar.zst
        destination: artifact-file2
    - store_artifacts:
        path: ../.cache/yay/
        destination: artifact-file3
    - store_artifacts:
        path: ../.cache/yay/${CIRCLE_JOB}
        destination: artifact-file5


# Main
version: 2
jobs:
  electron-ozone:
    <<: *defaults

workflows:
  version: 2
  build:
    jobs:
      - electron-ozone
